### ISSUE TITLE
Best Way to Parallelize Fitting

### ISSUE THREAD

**Issue by bonddr** [hsbadr/bayesian#11]
I noticed in the rdocumentation page that there are numerous ways to parallelize the fit for this process, including setting the "cores" argument, "threading" argument and setting future = T. I am wondering if there have been any time/functionality tests to understand the "best" way to do this, and also if there are vignettes/examples saved anywhere. I did not see a significant time increase from setting cores equal the number on my local machine.

**Comment by hsbadr** [comment]
The parallelization plan can be set using `future::plan()` (if `future = TRUE`) or via `cores` (number of cores) to use while `threads` control the within-chain parallelization. See https://paul-buerkner.github.io/brms/articles/brms_threading.html.

Tagging @paul-buerkner as he can provide more technical details.
