### ISSUE TITLE
Revise engine-specific encodings

### ISSUE THREAD

**Issue by hsbadr** [hsbadr/bayesian#4]
The options of engine-specific encodings dictate how the predictors should be handled and ensure that the data `parsnip` passes to `brms::brm` allows for a model fit that is as similar as possible to what it would have produced directly.
- `predictor_indicators` describes whether and how to create indicator/dummy variables from factor predictors.
    - `"none"`: do not expand factor predictors),
    - `"traditional"`: apply the standard `model.matrix()` encodings, and
    - `"one_hot"`: create the complete set including the baseline level for all factors.
    This encoding only affects cases when `fit.model_spec()` is used and the underlying model has an `x/y` interface. We currently use a `formula` interface.
- `compute_intercept` controls whether `model.matrix()` should include the intercept in its formula.
This affects more than the inclusion of an intercept column. With an intercept, `model.matrix()` computes dummy variables for all but one factor levels. Without an intercept, `model.matrix()` computes a full set of indicators for the first factor variable, but an incomplete set for the remainder.
- `remove_intercept` will remove the intercept column after `model.matrix()` is finished.
This can be useful if the model function automatically generates an intercept.
- `allow_sparse_x` specifies whether the model function can natively accommodate a sparse matrix representation for predictors during fitting and tuning.

@paul-buerkner Would you recommend changing any of the current options for the `brms` engine?

```r
    parsnip::set_encoding(
      model = "bayesian",
      eng = "brms",
      mode = "regression",
      options = list(
        predictor_indicators = "traditional",
        compute_intercept = TRUE,
        remove_intercept = TRUE,
        allow_sparse_x = FALSE
      )
    )
```

**Comment by paul-buerkner** [comment]
Looks good to me. I just have a question about `remove_intercept` to make sure: Since brms calls model.matrix internally (with an intercept unless excluded explicitely), `remove_intercept = TRUE` ensures the intercept is not included twice. Is that correct?

**Comment by hsbadr** [comment]
Yes. I opened this issue mainly to check if you'd prefer
- to not expand factor predictors (`predictor_indicators = "none"`) and/or
- to allow sparse matrix representation for predictors (`allow_sparse_x = TRUE`), if `brms::brm` does (or can) support it.

**Comment by paul-buerkner** [comment]
I see, thanks. I am just beginning to understand what `parsnip` does in the pre-processing.

- For some brms post-processing (e.g., `conditional_effects`) it is beneficial that brms itself still sees the factor not just the coded variables. This would mean favouring `predictor_indicators = "none"` right?
- brms can use Stan's sparse matrix algebra (see argument `sparse` in `brmsformula`) but does not itself handle sparse matrices as actually sparse. Also Stan's current sparse matrix algebra is quite slow so I would think that `allow_sparse_x = FALSE` is probably the better choice at the moment.

**Comment by hsbadr** [comment]
Perfect. That's exactly what I want. Yes, we'd favor `predictor_indicators = "none"`, if we ever decided to use an `x/y` interface (we currently use the `formula` interface, which makes this option irrelevant) and keep sparse `x` disallowed.
