### ISSUE TITLE
Allow to specify non-linear models in the add_model interface

### ISSUE THREAD

**Issue by DoktorMike** [hsbadr/bayesian#6]
Currently, as far as I can see, only linear models are allowed. It would be neat if the non-linear models from brms are also allowed in this interface.

**Comment by hsbadr** [comment]
You can actually specify nonlinear models via `bayesian(formula.override = bayesian_formula(...), ...)` while using a linear formula for data preprocessing, which has to include all required variables (see https://hsbadr.github.io/bayesian/articles/GetStarted.html).

`formula.override` can be any formula generated by `bayesian_formula` (equivalent to `brms::brmsformula`) which is passed to `brms::brm()` to fit a (non-)linear model. Let me know if you run into any issues.

**Comment by DoktorMike** [comment]
Apologies. I must have missed that. I'll try this out. Thanks for the quick response and the efforts!

**Comment by hsbadr** [comment]
No worries. I'm closing this now; feel free to open a new issue if needed. Thanks!
